image: beevee/dotfox:latest

stages:
    - build

check_unchecked:
    stage: build
    script:
        - "whoami"
        - "ls -lah /"
        - "dotnet run --project console-runner/console-runner.csproj -- check-unchecked -g geckodriver_docker"
    when: manual
