image: beevee/dotfox:latest

stages:
    - test
    - deploy

check_unchecked:
    stage: test
    script:
        - "dotnet run --project console-runner/console-runner.csproj -- check-unchecked -g geckodriver_docker"
    only:
        - schedules

submit:
    stage: deploy
    script:
        - "dotnet run --project console-runner/console-runner.csproj -- submit -z solutions"
        - "curl -F \"private_id=5105068979550d027d0d93ba\" -F \"file=@console-runner/submissions/solutions.zip\" https://monadic-lab.org/submit"
    when: manual