image: beevee/dotfox:latest

stages:
    - test
    - deploy

check_unchecked:
    stage: test
    script:
        - "dotnet run --project console-runner/console-runner.csproj -- check-unchecked -g geckodriver_docker"
    when: manual

submit:
    stage: deploy
    script:
        - "dotnet run --project console-runner/console-runner.csproj -- submit"
    when: manual