image: beevee/dotfox:latest

stages:
    - compare_csv
    - submit
    - solve_block

#check_unchecked:scheduled:
#    stage: test
#    script:
#        - "dotnet run -c Release --project console-runner/console-runner.csproj -- check-unchecked -g geckodriver_docker"
#    only:
#        - schedules
#
#check_unchecked:
#    stage: test
#    script:
#        - "dotnet run -c Release --project console-runner/console-runner.csproj -- check-unchecked -g geckodriver_docker"
#    when: manual

compare_csv:scheduled:
    stage: compare_csv
    before_script:
        - "pip3 install -r lambda-client/requirements.txt"
    script:
        - "cd lambda-client && python3 lambdad.py &"
        - "dotnet run -c Release --project console-runner/console-runner.csproj -- csv > our.csv"
        - "curl -s https://monadic-lab.org/grades/5105068979550d027d0d93ba/$(curl -s https://monadic-lab.org/grades/5105068979550d027d0d93ba/submissions.txt | tail -1 | cut -d ' ' -f 1)/score.csv > their.csv"
        - "diff --unified=0 --ignore-trailing-space our.csv their.csv"
    allow_failure: false
    only:
        - schedules

submit:
    stage: submit
    before_script:
        - "pip3 install -r lambda-client/requirements.txt"
    script:
        - "cd lambda-client && python3 lambdad.py &"
        - "dotnet run -c Release --project console-runner/console-runner.csproj -- submit -z solutions"
        - "curl -s -F \"private_id=5105068979550d027d0d93ba\" -F \"file=@console-runner/submissions/solutions.zip\" https://monadic-lab.org/submit"
    when: on_failure

solve_block:
    stage: solve_block
    before_script:
        - "pip3 install -r lambda-client/requirements.txt"
    script:
        - "cd lambda-client && python3 lambdad.py &"
        - "dotnet run -c Release --project console-runner/console-runner.csproj -- solve-block -s"
    when: manual
