image: beevee/dotfox:latest

stages:
    - build

check_unchecked:
    stage: build
    script:
        - "./geckodriver_docker32"
        # - "dotnet run --project console-runner/console-runner.csproj -- check-unchecked -g geckodriver_docker32"
    when: manual
